version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: react-node-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: react_node_app
    volumes:
      - mongodb_data:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=4000
      - ATLAS_URL=mongodb://admin:password123@mongodb:27017/react_node_app?authSource=admin
    depends_on:
      - mongodb

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  mongodb_data:
    driver: local
